### ISSUE TITLE
Failure: Shipment/ReferenceNumber is not allowed for this shipment (120541)

### ISSUE THREAD

**Issue by TuhiranDevbhuti** [gabrielbull/php-ups-api#341] opened 2022-04-07 10:41 UTC
Hello @Rud5G @thijsw @okj579 @MPiccinato @JREAM
I'm facing the following  issue while integrating the shipping API. Please Help me out.
![127-0-0-1-3000-test-ups](https://user-images.githubusercontent.com/48747782/162181397-30213e0f-b359-4294-b40f-1c6bcb6f61fb.png)

**Comment by mfrederico** [comment] 2022-04-08 21:31
I had the same issue - I fixed it by changing it from S_STANDARD to S_GROUND

**Comment by mfrederico** [comment] 2022-04-08 21:35
Duplicate of #333 327

**Closed** 2022-04-09 05:11 UTC
